# Generated by Django 3.2.9 on 2021-11-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='', max_length=70)),
                ('prenume', models.CharField(default='', max_length=70)),
                ('cnp', models.PositiveBigIntegerField(default='', max_length=30)),
                ('data_nastere', models.CharField(default='', max_length=40)),
                ('data_inregistrare', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Masina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=70)),
                ('an', models.IntegerField(default='0', max_length=10)),
                ('km', models.IntegerField(default='0', max_length=10)),
                ('garantie', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Tranzactie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_masina', models.CharField(default='', max_length=70)),
                ('id_card_client', models.CharField(default='', max_length=70)),
                ('suma_piese', models.IntegerField(default='0', max_length=20)),
                ('suma_manopera', models.IntegerField(default='0', max_length=20)),
                ('data_tranzactie', models.DateField(auto_now=False, auto_now_add=False)),
                ('ora', models.TimeField(auto_now=False, auto_now_add=False)),
            ],
        ),
    ]
